# Generated by Django 3.2.9 on 2021-12-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_devices_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='device',
        ),
        migrations.AddField(
            model_name='devices',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app1.messages'),
        ),
    ]
